name: first

on:
  push:
    branches: main
    
  workflow_dispatch:

jobs:
  job1:
    name: First Job
    runs-on: ubuntu_latest
    steps:
      - name: Job1 Step One
        uses: actions/checkout@v2
      - name: Job1 Step Two
        run: env | sort 
      - name: Job1 Step Three
        run: date
  job2:
    name: Second Job
    runs-on: windows_latest
    steps:
      - name: Job2 Step One
        uses: actions/checkout@v2
      - name: Job2 Step Two
        run: "Get-ChildItem Env: | Sort-Object Name"
  job3:
    name: Third Job
    runs-on: macos_latest
    steps:
      - name: Job2 Step One
        uses: actions/checkout@v2
      - name: Job2 Step Two
        run: "Get-ChildItem Env: | Sort-Object Name"
  job4:
    name: depends job
    needs: [job1, job2]
    runs-on: macos_latest
    steps:
      - name: Depends Job Step One
        run: date
        
  
  
  

